// data.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/data.proto

package pb

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataService_GetDataById_FullMethodName         = "/data.DataService/GetDataById"
	DataService_ListDataByTimeRange_FullMethodName = "/data.DataService/ListDataByTimeRange"
)

// DataServiceClient is the client API for DataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataServiceClient interface {
	GetDataById(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetDataByIDRequest, Data], error)
	ListDataByTimeRange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse], error)
}

type dataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataServiceClient(cc grpc.ClientConnInterface) DataServiceClient {
	return &dataServiceClient{cc}
}

func (c *dataServiceClient) GetDataById(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetDataByIDRequest, Data], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[0], DataService_GetDataById_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetDataByIDRequest, Data]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_GetDataByIdClient = grpc.BidiStreamingClient[GetDataByIDRequest, Data]

func (c *dataServiceClient) ListDataByTimeRange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataService_ServiceDesc.Streams[1], DataService_ListDataByTimeRange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ListDataByTimeRangeClient = grpc.BidiStreamingClient[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse]

// DataServiceServer is the server API for DataService service.
// All implementations must embed UnimplementedDataServiceServer
// for forward compatibility.
type DataServiceServer interface {
	GetDataById(grpc.BidiStreamingServer[GetDataByIDRequest, Data]) error
	ListDataByTimeRange(grpc.BidiStreamingServer[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse]) error
	mustEmbedUnimplementedDataServiceServer()
}

// UnimplementedDataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataServiceServer struct{}

func (UnimplementedDataServiceServer) GetDataById(grpc.BidiStreamingServer[GetDataByIDRequest, Data]) error {
	return status.Errorf(codes.Unimplemented, "method GetDataById not implemented")
}
func (UnimplementedDataServiceServer) ListDataByTimeRange(grpc.BidiStreamingServer[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ListDataByTimeRange not implemented")
}
func (UnimplementedDataServiceServer) mustEmbedUnimplementedDataServiceServer() {}
func (UnimplementedDataServiceServer) testEmbeddedByValue()                     {}

// UnsafeDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataServiceServer will
// result in compilation errors.
type UnsafeDataServiceServer interface {
	mustEmbedUnimplementedDataServiceServer()
}

func RegisterDataServiceServer(s grpc.ServiceRegistrar, srv DataServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataService_ServiceDesc, srv)
}

func _DataService_GetDataById_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).GetDataById(&grpc.GenericServerStream[GetDataByIDRequest, Data]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_GetDataByIdServer = grpc.BidiStreamingServer[GetDataByIDRequest, Data]

func _DataService_ListDataByTimeRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DataServiceServer).ListDataByTimeRange(&grpc.GenericServerStream[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataService_ListDataByTimeRangeServer = grpc.BidiStreamingServer[ListDataByTimeRangeRequest, ListDataByTimeRangeResponse]

// DataService_ServiceDesc is the grpc.ServiceDesc for DataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "data.DataService",
	HandlerType: (*DataServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetDataById",
			Handler:       _DataService_GetDataById_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ListDataByTimeRange",
			Handler:       _DataService_ListDataByTimeRange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/data.proto",
}
