// data.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: proto/data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Single request
type GetDataByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDataByIDRequest) Reset() {
	*x = GetDataByIDRequest{}
	mi := &file_proto_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDataByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataByIDRequest) ProtoMessage() {}

func (x *GetDataByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataByIDRequest.ProtoReflect.Descriptor instead.
func (*GetDataByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{0}
}

func (x *GetDataByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Request of packet
type ListDataByTimeRangeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataByTimeRangeRequest) Reset() {
	*x = ListDataByTimeRangeRequest{}
	mi := &file_proto_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataByTimeRangeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataByTimeRangeRequest) ProtoMessage() {}

func (x *ListDataByTimeRangeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataByTimeRangeRequest.ProtoReflect.Descriptor instead.
func (*ListDataByTimeRangeRequest) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{1}
}

func (x *ListDataByTimeRangeRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ListDataByTimeRangeRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

// Single response or part of packet response
type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Max           int32                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_proto_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Data) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Data) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

// Packet response
type ListDataByTimeRangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DataItems     []*Data                `protobuf:"bytes,1,rep,name=data_items,json=dataItems,proto3" json:"data_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDataByTimeRangeResponse) Reset() {
	*x = ListDataByTimeRangeResponse{}
	mi := &file_proto_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDataByTimeRangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDataByTimeRangeResponse) ProtoMessage() {}

func (x *ListDataByTimeRangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDataByTimeRangeResponse.ProtoReflect.Descriptor instead.
func (*ListDataByTimeRangeResponse) Descriptor() ([]byte, []int) {
	return file_proto_data_proto_rawDescGZIP(), []int{3}
}

func (x *ListDataByTimeRangeResponse) GetDataItems() []*Data {
	if x != nil {
		return x.DataItems
	}
	return nil
}

var File_proto_data_proto protoreflect.FileDescriptor

const file_proto_data_proto_rawDesc = "" +
	"\n" +
	"\x10proto/data.proto\x12\x04data\"$\n" +
	"\x12GetDataByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"@\n" +
	"\x1aListDataByTimeRangeRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\"F\n" +
	"\x04Data\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\"H\n" +
	"\x1bListDataByTimeRangeResponse\x12)\n" +
	"\n" +
	"data_items\x18\x01 \x03(\v2\n" +
	".data.DataR\tdataItems2\xa6\x01\n" +
	"\vDataService\x127\n" +
	"\vGetDataById\x12\x18.data.GetDataByIDRequest\x1a\n" +
	".data.Data(\x010\x01\x12^\n" +
	"\x13ListDataByTimeRange\x12 .data.ListDataByTimeRangeRequest\x1a!.data.ListDataByTimeRangeResponse(\x010\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_proto_data_proto_rawDescOnce sync.Once
	file_proto_data_proto_rawDescData []byte
)

func file_proto_data_proto_rawDescGZIP() []byte {
	file_proto_data_proto_rawDescOnce.Do(func() {
		file_proto_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)))
	})
	return file_proto_data_proto_rawDescData
}

var file_proto_data_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_data_proto_goTypes = []any{
	(*GetDataByIDRequest)(nil),          // 0: data.GetDataByIDRequest
	(*ListDataByTimeRangeRequest)(nil),  // 1: data.ListDataByTimeRangeRequest
	(*Data)(nil),                        // 2: data.Data
	(*ListDataByTimeRangeResponse)(nil), // 3: data.ListDataByTimeRangeResponse
}
var file_proto_data_proto_depIdxs = []int32{
	2, // 0: data.ListDataByTimeRangeResponse.data_items:type_name -> data.Data
	0, // 1: data.DataService.GetDataById:input_type -> data.GetDataByIDRequest
	1, // 2: data.DataService.ListDataByTimeRange:input_type -> data.ListDataByTimeRangeRequest
	2, // 3: data.DataService.GetDataById:output_type -> data.Data
	3, // 4: data.DataService.ListDataByTimeRange:output_type -> data.ListDataByTimeRangeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_data_proto_init() }
func file_proto_data_proto_init() {
	if File_proto_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_data_proto_rawDesc), len(file_proto_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_data_proto_goTypes,
		DependencyIndexes: file_proto_data_proto_depIdxs,
		MessageInfos:      file_proto_data_proto_msgTypes,
	}.Build()
	File_proto_data_proto = out.File
	file_proto_data_proto_goTypes = nil
	file_proto_data_proto_depIdxs = nil
}
